loki:
  auth_enabled: false
  
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: "168h"
    max_cache_freshness_per_query: "10m"
    split_queries_by_interval: "15m"
    retention_period: "48h"
compactor:
  retention_enabled: true
  working_directory: /var/loki/compactor/retention
minio:
  enabled: true
  metrics:
    serviceMonitor:
      enabled: true
      includeNode: true
      additionalLabels:
        release: monitoring
monitoring:
  dashboards:
    namespace: "monitoring"
  serviceMonitor:
    labels:
      release: monitoring
      
read:
  affinity: {}
write:
  affinity: {}